# Generated by Django 3.2.10 on 2022-07-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0006_alter_cloudconnection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='access_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
